name: Nightly built Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v1

    - name: install_dependencies
      run: |
        sudo apt-get -y update 
        sudo apt-get -ym install libsdl2-dev
        sudo apt-get -ym install libfreetype6-dev
        sudo apt-get -ym install libminiupnpc-dev
        sudo apt-get -ym install libbz2-dev

    - name: CI-Build
      run: sh ./.github/build-ubuntu.sh
      
    - name: Upload the executable
      uses: actions/upload-artifact@v2
      with:
        name: sim-linux-OTRP
        path: ./sim-linux-OTRP
